kevcat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
  path('', views.index, name='index'),
  path('merch', views.merch, name='merch'),
  path('music', views.music, name='music'),
  path('privacy-policy', views.privacy_policy, name='privacy_policy'),
  path('refund-policy', views.refund_policy, name='refund_policy'),
  path('shipping-policy', views.shipping_policy, name='shipping_policy')
]

store/models.py
from django.db import models

class Product(models.Model):
  CATEGORIES = [
    ('beanies', 'Beanies'),
    ('caps', 'Caps'),
    ('hoodies', 'Hoodies'),
    ('sweaters', 'Sweaters'),
    ('tshirts', 'T-Shirts')
  ]
  

  name = models.CharField(max_length=50, default='KevCat merch')
  image = models.ImageField(upload_to='./store/static/store/images/products')
  price = models.FloatField()
  category = models.CharField(max_length=20, choices=CATEGORIES)

  def __str__(self):
    return f'{self.name} ({self.category})'

store/views.py
from random import shuffle

from django.shortcuts import render

from .models import *

# Create your views here.
def index(request):
  caps = Product.objects.filter(category='caps')[:2]
  hoodies = Product.objects.filter(category='hoodies')[:2]
  tshirts = Product.objects.filter(category='tshirts')[:4]
  products = list(caps) + list(hoodies) + list(tshirts)
  shuffle(products)
  return render(request, 'store/index.html', {
    'products': products
  })

def merch(request):
  products = Product.objects.all()
  return render(request, 'store/merch.html', {
    'beanies': [product for product in products if product.category == 'beanies'],
    'caps': [product for product in products if product.category == 'caps'],
    'hoodies': [product for product in products if product.category == 'hoodies'],
    'sweaters': [product for product in products if product.category == 'sweaters'],
    'tshirts': [product for product in products if product.category == 'tshirts']
  })

def music(request):
  return render(request, 'store/music.html')

def privacy_policy(request):
  return render(request, 'store/privacy_policy.html')

def refund_policy(request):
  return render(request, 'store/refund_policy.html')

def shipping_policy(request):
  return render(request, 'store/shipping_policy.html')

store/templates/store/index.html
{% extends 'store/layout.html' %}

{% load static %}

{% load store_extras %}

{% block title %} Home {% endblock %}

{% block body %}

<div class='container'>
  <section class='row hero-section align-items-center'>
    <div class='col-12 col-md-6 d-flex justify-content-center mb-5 mb-md-0'>
      <div class='img-wrapper'>
        <img class='img-1' src='https://images.unsplash.com/photo-1545224144-b38cd309ef69' alt='Kevin Perfoming'>
      </div>

      <div class='img-wrapper'>
        <img class='img-2' src='https://images.unsplash.com/photo-1574232861722-d1e837e4b0f0' alt='Kevin Perfoming'>
      </div>
    </div>
    <div class='col-12 col-md-6 hero-text text-center mt-5 mt-md-0'>Feel the beat, embrace the rhythm, and join the KevCat experience.</div>
  </section>

  <section class='row'>
    <div class='col d-flex justify-content-center'>
      <button class='d-flex align-items-center listen-spotify'>
        <span class='me-2'>Listen on Spotify</span>
        <i class='bi bi-arrow-right'></i>
      </button>
    </div>
  </section>

  <section class='row row-cols-2 row-cols-md-4 gy-5 merch-section'>
    {% for product in products %}
      <div class='col hidden hidden-center'>
        <div class='img-wrapper'>
          <img src='{{ product.image|image }}' alt='merch' />
        </div>
        <div class='info-container'>
          <div class='name'>{{ product.name }}</div>
          <div class='price'>R{{ product.price|floatformat:2 }}</div>
        </div>
      </div>
    {% endfor %}
  </section>

  <section class='row'>
    <div class='col d-flex justify-content-center'>
      <button class='d-flex align-items-center buy'>
        <span class='me-2'>Buy now!</span>
        <i class='bi bi-arrow-right'></i>
      </button>
    </div>
  </section>

  <section class='row info-section'>
    <div class='col-12 col-md-6 d-flex flex-column align-items-center hidden hidden-left mb-5 mb-md-0'>
      <p>Welcome to the official merchandise and music store for KevCat! Here, you can find everything from exclusive music releases to limited edition t-shirts, hats, and accessories. We pride ourselves on providing our fans with high-quality, unique merchandise that reflects the spirits and style of our music. With a wide range of sizes and styles, there's something for everyone in our collection. And as always, thank for supporting KevCat. We couldn't do it without you!</p>
      <div>
        <button class='d-flex align-items-center listen'>
          <span class='me-2'>Listen now!</span>
          <i class='bi bi-arrow-right'></i>
        </button>
      </div>
    </div>

    <div class='col-12 col-md-6 d-flex flex-column align-items-end hidden hidden-right'>
      <img src='{% static "store/images/brand/logo.jpg" %}' alt='song-cover' class='mb-3'/>
      <audio class='d-block' controls>
        <source src='{% static "store/audio/music.mp3" %}'>
      </audio>
    </div>
  </section>
</div>

<script type='text/javascript'>
  document.querySelector('.home-nav').classList.add('active');

  document.querySelector('.listen-spotify').addEventListener('click', () => {
    window.location.href = 'https://open.spotify.com/artist/0Uy8T1f9ABGEq1pXzYEmv0';
  });

  document.querySelector('.buy').addEventListener('click', () => {
    window.location.href = '/merch';
  });

  document.querySelector('.listen').addEventListener('click', () => {
    window.location.href = '/music';
  });
</script>

<script src='{% static "store/js/index.js" %}'></script>

{% endblock %}

store/templates/store/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css' rel='stylesheet'
    integrity='sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65' crossorigin='anonymous'>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
  <script src='https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js'
    integrity='sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3'
    crossorigin='anonymous'></script>
  <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js'
    integrity='sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V'
    crossorigin='anonymous'></script>
  <link rel='stylesheet' href='../../static/store/styles.css'>
  <title>KevCat: {% block title %}{% endblock %}</title>
</head>

<body>

  <header class='d-flex justify-content-between align-items-center'>
    <div class='brand d-flex align-items-center'>
      <span class='ms-2'><a href='{% url "store:index" %}'>KevCat</a></span>
    </div>
    <nav class='d-flex'>
      <div class='home-nav'><a href='{% url "store:index" %}'>Home</a></div>
      <div class='merch-nav'><a href='{% url "store:merch" %}'>Merch</a></div>
      <div class='music-nav'><a href='{% url "store:music" %}'>Music</a></div>
    </nav>
  </header>

  <main>
    {% block body %}{% endblock %}
  </main>

  <footer>
    <div class='d-flex flex-column flex-md-row align-items-center align-items-md-start justify-content-between mb-5 flex-wrap w-100'>
      <div>
        <div class='d-flex flex-column align-items-center align-items-md-start mb-5'>
          <div class='title'>Get In Touch</div>
          <div class='d-flex align-items-center ms-1'>
            <i class='bi bi-facebook'></i>
            <span class='ms-2'><a href='https://web.facebook.com/profile.php?id=100007176047901' target='_blank'>Facebook</a></span>
          </div>
          <div class='d-flex align-items-center ms-1'>
            <i class='bi bi-instagram'></i>
            <span class='ms-2'><a href='https://www.instagram.com/kevcat_official/' target='_blank'>Instagram</a></span>
          </div>
          <div class='d-flex align-items-center ms-1'>
            <i class='bi bi-whatsapp'></i>
            <span class='ms-2'><a href='https://wa.me/27724403980'>WhatsApp</a></span>
          </div>
        </div>
  
        <div class='d-flex flex-column align-items-center align-items-md-start mb-5'>
          <div class='title'>Our Policies</div>
          <div class='d-flex align-content-center ms-1'>
            <a href='{% url "store:privacy_policy" %}'>Privacy Policy</a>
          </div>
          <div class='d-flex align-content-center ms-1'>
            <a href='{% url "store:refund_policy" %}'>Refund Policy</a>
          </div>
          <div class='d-flex align-content-center ms-1'>
            <a href='{% url "store:shipping_policy" %}'>Shipping Policy</a>
          </div>
        </div>
      </div>
  
      <div class='text-center'>
        <div class='brand'>The Next Big Thing</div>
        <div>[Logo Goes Here]</div>
      </div>
    </div>

    <div class='copyright'>&copy KevCat 2023</div>
  </footer>

</body>

<script type='text/javascript'>
  const observer = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.remove('hidden-center', 'hidden-left', 'hidden-right');
    } 
  });
});

const elementToObserve = document.querySelectorAll('.hidden');
elementToObserve.forEach((element) => observer.observe(element));

</script>

<script type='text/javascript' src='{% static "store/js/script.js" %}'></script>

</html>

store/templates/store/merch.html
{% extends 'store/layout.html' %}

{% load static %}

{% load store_extras %}

{% block title %} Merch {% endblock %}

{% block body %}

<div class='merch-hero d-flex'>
  <div class='w-60'>
    <div class='img-wrapper shade'>
      <img src='https://images.unsplash.com/photo-1470225620780-dba8ba36b745' alt='listening-to-music' />
    </div>
    <div class='merch-hero-text'>Experience the magic of KevCat and discover a new level of quality and style.</div>
  </div>
  <div class='w-40 carousel'>
    <div class='img-wrapper'>
      <img class='carousel-img' src='https://images.unsplash.com/photo-1620578077783-33e254311182' alt='listening-to-music' />
    </div>
    <div class='carousel-controls'>
      <div class='prev carousel-control'></div>
      <div class='current selected carousel-control'></div>
      <div class='next carousel-control'></div>
    </div>
  </div>
</div>

<div class='container'>

  <section class='merch-section beanies'>
    <div class='title text-center'>Beanies</div>
    <div class='row row-cols-2 row-cols-md-4 gy-5 '>
      {% for beanie in beanies %}
        <div class='col hidden hidden-center'>
          <div class='img-wrapper'>
            <img class='skeleton' src='{{ beanie.image|image }}' alt='merch' loading='lazy'/>
          </div>
          <div class='info-container'>
            <div class='name'>{{ beanie.name }}</div>
            <div class='price'>R{{ beanie.price|floatformat:2 }}</div>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>

  <section class='merch-section caps'>
    <div class='title text-center'>Caps</div>
    <div class='row row-cols-2 row-cols-md-4 gy-5 '>
      {% for cap in caps %}
        <div class='col hidden hidden-center'>
          <div class='img-wrapper'>
            <img class='skeleton' src='{{ cap.image|image }}' alt='merch' loading='lazy'/>
          </div>
          <div class='info-container'>
            <div class='name'>{{ cap.name }}</div>
            <div class='price'>R{{ cap.price|floatformat:2 }}</div>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>

  <section class='merch-section hoodies'>
    <div class='title text-center'>Hoodies</div>
    <div class='row row-cols-2 row-cols-md-4 gy-5'>
      {% for hoodie in hoodies %}
        <div class='col hidden hidden-center'>
          <div class='img-wrapper'>
            <img class='skeleton' src='{{ hoodie.image|image }}' alt='merch' loading='lazy' />
          </div>
          <div class='info-container'>
            <div class='name'>{{ hoodie.name }}</div>
            <div class='price'>R{{ hoodie.price|floatformat:2 }}</div>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>

  <section class='merch-section sweaters'>
    <div class='title text-center'>Sweaters</div>
    <div class='row row-cols-2 row-cols-md-4 gy-5 '>
      {% for sweater in sweaters %}
        <div class='col hidden hidden-center'>
          <div class='img-wrapper'>
            <img class='skeleton' src='{{ sweater.image|image }}' alt='merch' loading='lazy'/>
          </div>
          <div class='info-container'>
            <div class='name'>{{ sweater.name }}</div>
            <div class='price'>R{{ sweater.price|floatformat:2 }}</div>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>

  <section class='merch-section t-shirts'>
    <div class='title text-center'>T-shirts</div>
    <div class='row row-cols-2 row-cols-md-4 gy-5 '>
      {% for tshirt in tshirts %}
        <div class='col hidden hidden-center'>
          <div class='img-wrapper'>
            <img class='skeleton' src='{{ tshirt.image|image }}' alt='merch' loading='lazy'/>
          </div>
          <div class='info-container'>
            <div class='name'>{{ tshirt.name }}</div>
            <div class='price'>R{{ tshirt.price|floatformat:2 }}</div>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>

</div>

<script type='text/javascript'>
  document.querySelector('.merch-nav').classList.add('active');
</script>

<script src='{% static "store/js/merch.js" %}'></script>

{% endblock %}

store/templates/store/music.html
{% extends 'store/layout.html' %}

{% load static %}

{% block title %} Music {% endblock %}

{% block body %}

<div class='merch-hero d-flex'>
  <div class='w-60'>
    <div class='img-wrapper shade'>
      <img src='https://images.unsplash.com/photo-1615554851544-e6249b92a492' alt='listening-to-music' />
    </div>
    <div class='music-hero-text'>
      <div class='line'>I'm spitting fire, got flames in my mouth</div>
      <div class='line current'>My rhymes so hot, they make the devil come out</div>
      <div class='line'>I'm the king of the mic, the ruler of the beat</div>
    </div>
  </div>
  <div class='w-40'>
    <div class='img-wrapper'>
      <img src='https://images.unsplash.com/photo-1625786682948-2168238883d2' alt='listening-to-music' />
    </div>
  </div>
</div>

<div class='container'>
  <section class='row music-intro'>
    <div class='title text-center'>Music</div>

    <div class='col-12 col-lg-8 hidden hidden-left'>
      <p>At the heart of KevCat's music and brand lies a deep sense of passion and creativity. With their unique sound and lyrics, KevCat has become synonymous with the cutting edge of modern music. Drawing on a wide range of influences, from classic rock to hip-hop, KevCat's music is a reflection of their commitment to innovation and self-expression. But beyond the music, KevCat's brand is about more than just sound. It's a lifestyle, a way of thinking and feeling that connects with fans on a deep, emotional level. Whether through their live performances or their merchandise, KevCat is dedicated to creating an experience that is both authentic and inspiring. With a focus on quality and style, KevCat is more than just a music artist - they are a movement.</p>
    </div>

    <div class='col-6  col-lg-4 d-none d-lg-flex justify-content-end hidden hidden-right'>
      <div class='img-wrapper'>
        <img src='https://images.unsplash.com/photo-1495175448924-1d9a30c90a42' alt='Picture by Konstantine Dyadyun' />
      </div>
    </div>
  </section>

  <section class='row hits-section'>
    <div class='text-center title'>New Hits</div>
    <div class='col-12 col-md-12 col-lg-6 mb-5 mb-lg-0 hidden hidden-left'>

      <div class='song-wrapper'>
        <div class='song'>
          <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3 new-hit'/>
          <div class='song-name'>Song Name</div>
          <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
        </div>
          <audio  class='new-hit' controls>
            <source src='{% static "store/audio/music.mp3" %}'>
          </audio>
      </div>

    </div>
    <div class='col-12 col-md-12 col-lg-6 d-flex flex-column align-items-center small-music-container justify-content-between hidden hidden-right'>
      <div class='d-flex justify-content-end mb-5 mb-lg-0 right-song-container'>
        <div class='song-wrapper font-small'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3' />
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
          </div>
          <audio controls>
            <source src='{% static "store/audio/music.mp3" %}'>
          </audio>
        </div>

        <div class='song-wrapper font-small d-flex flex-column align-items-center'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3'/>
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
          </div>
            <audio controls>
              <source src='{% static "store/audio/music.mp3" %}'>
            </audio>
        </div>
      </div>

      <button class='d-flex align-items-center listen-spotify'>
        <span class='me-2'>Listen on Spotify</span>
        <i class='bi bi-arrow-right'></i>
      </button>
    </div>
  </section>

  <section class='more-songs-section'>
    <div class='text-center title'>More Songs</div>

    <div class='row row-cols-2 row-cols-lg-4 gy-5'>
      <div class='col hidden hidden-center'>
        <div class='song-wrapper'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3'/>
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
          </div>
            <audio controls>
              <source src='{% static "store/audio/music.mp3" %}'>
            </audio>
        </div>
      </div>
      <div class='col hidden hidden-center'>
        <div class='song-wrapper'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3'/>
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
          </div>
            <audio controls>
              <source src='{% static "store/audio/music.mp3" %}'>
            </audio>
        </div>
      </div>
      <div class='col hidden hidden-center'>
        <div class='song-wrapper'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3'/>
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
          </div>
            <audio controls>
              <source src='{% static "store/audio/music.mp3" %}'>
            </audio>
        </div>
      </div>
      <div class='col hidden hidden-center'>
        <div class='song-wrapper'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3'/>
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
          </div>
            <audio controls>
              <source src='{% static "store/audio/music.mp3" %}'>
            </audio>
        </div>
      </div>
      <div class='col hidden hidden-center'>
        <div class='song-wrapper'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3'/>
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
          </div>
            <audio controls>
              <source src='{% static "store/audio/music.mp3" %}'>
            </audio>
        </div>
      </div>
      <div class='col hidden hidden-center'>
        <div class='song-wrapper'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3'/>
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
          </div>
            <audio controls>
              <source src='{% static "store/audio/music.mp3" %}'>
            </audio>
        </div>
      </div>
      <div class='col hidden hidden-center'>
        <div class='song-wrapper'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3'/>
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle' data-playing='false'><i class='bi bi-play-fill'></i></div>
          </div>
            <audio controls>
              <source src='{% static "store/audio/music.mp3" %}'>
            </audio>
        </div>
      </div>
      <div class='col hidden hidden-center'>
        <div class='song-wrapper'>
          <div class='song'>
            <img src='https://images.unsplash.com/photo-1505740420928-5e560c06d30e' alt='song-cover' class='mb-3'/>
            <div class='song-name'>Song Name</div>
            <div data-playing='false' class='pause-play-toggle'><i class='bi bi-play-fill'></i></div>
          </div>
            <audio controls>
              <source src='{% static "store/audio/music.mp3" %}'>
            </audio>
        </div>
      </div>

    </div>

  </section>
</div>

<script type='text/javascript'>
  document.querySelector('.music-nav').classList.add('active');

  document.querySelector('.listen-spotify').addEventListener('click', () => {
    window.location.href = 'https://open.spotify.com/artist/0Uy8T1f9ABGEq1pXzYEmv0';
  });
</script>

<script type='text/javascript' src='{% static "store/js/music.js" %}'></script>

{% endblock %}

store/templates/store/privacy_policy.html
{% extends 'store/layout.html' %}

{% block title %} Privacy Policy {% endblock %}

{% block body %}

<section class='container'>
  <div class='title text-center'>Privacy Policy</div>

  <div class='mb-5'>
    <p>KevCat is committed to protecting the privacy of our customers. This privacy policy outlines the types of personal information we collect, how we use that information, and the measures we take to protect your privacy.</p>
  </div>
  
  <div class='mb-5'>
    <h4>Information We Collect</h4>

    <p>When you make a purchase on our website, we collect certain personal information such as your name, email address, phone number, and shipping address. We also collect information about your purchase history, including the products you have purchased and the dates of those purchases.</p>

    <p>In addition, we may collect certain non-personal information such as your IP address, browser type, and operating system. This information is used to improve the performance and functionality of our website.</p>
  </div>

  <div class='mb-5'>
    <h4>How We Use Your Information</h4>
  
    <p>We use your personal information to process your orders and to provide you with a better shopping experience. This includes communicating with you about your orders and providing you with information about our products and promotions. We may also use your information to conduct market research and to improve the functionality of our website.</p>
  
    <p>We do not sell or share your personal information with third parties except as necessary to process your orders or as required by law. We may share your information with our trusted partners who provide services on our behalf, such as shipping and payment processing. These partners are required to maintain the confidentiality and security of your personal information.</p>
  </div>

  <div class='mb-5'>
    <h4>Security Measures</h4>
  
    <p>We take the security of your personal information very seriously. We use a variety of physical, electronic, and managerial measures to protect your personal information from unauthorized access, use, or disclosure. We also use SSL (Secure Sockets Layer) encryption to protect your personal information when it is transmitted over the internet.</p>
  </div>

  <div class='mb-5'>
    <h4>Third-Party Links</h4>
  
    <p>Our website may contain links to third-party websites that are not affiliated with KevCat. We are not responsible for the privacy practices or content of these third-party websites. We encourage you to review the privacy policies of these websites before providing any personal information.</p>
  </div>

  <div class='mb-5'>
    <h4>Changes to the Privacy Policy</h4>
  
    <p>We may update our privacy policy from time to time to reflect changes in our business practices or legal requirements. We will post any updates to our website and will notify you of any material changes to our privacy policy.</p>
  </div>

  <div class='mb-5'>
    <h4>Conclusion</h4>
  
    <p>At KevCat, we are committed to protecting your privacy and personal information. Our privacy policy reflects our commitment to transparency, security, and trust. If you have any questions or concerns regarding our privacy policy, please do not hesitate to contact us.</p>
  </div>


</section>

{% endblock %}

store/templates/store/refund_policy.html
{% extends 'store/layout.html' %}

{% block title %} Refund Policy {% endblock %}

{% block body %}

<section class='container'>
  <div class='mb-5'>
    <div class='title text-center'>Refund Policy</div>
    
    <p>At KevCat, we strive to provide our customers with high-quality products and excellent customer service. However, we understand that there may be situations where a refund is necessary. That's why we have established a comprehensive refund policy that covers various aspects of the refund process. In this essay, we will discuss the key elements of our refund policy.</p>
  </div>

  <div class='mb-5'>
    <h4>Eligibility for Refunds</h4>
  
    <p>To be eligible for a refund, the following conditions must be met:
      <ul>
        <li>The item must be returned within 30 days of purchase.</li>
        <li>The item must be in its original condition with all tags attached.</li>
        <li>The item must be accompanied by a copy of the receipt or proof of purchase.</li>
        <li>If these conditions are not met, we reserve the right to refuse a refund.</li>
      </ul>
    </p>
  </div>

  <div class='mb-5'>
    <h4>Refund Process</h4>
  
    <p>To initiate a refund, please contact our customer service team via email or phone. We will provide you with a return shipping label, and you will be responsible for the return shipping costs. Once we receive the returned item, we will inspect it and notify you of the status of your refund. If your refund is approved, we will initiate a refund to your original payment method. Please note that it may take several business days for the refund to appear on your account.</p>
  </div>

  <div class='mb-5'>
    <h4>Exchanges</h4>
  
    <p>If you would like to exchange an item, please follow the same process as outlined above for a refund. However, please note that exchanges are subject to availability. If the item you would like to exchange for is not available, we will provide you with a refund instead.</p>
  </div>

  <div class='mb-5'>
    <h4>Damaged or Defective Items</h4>
  
    <p>If you receive a damaged or defective item, please contact our customer service team within 7 days of receiving the item. We will provide you with a return shipping label, and we will cover the return shipping costs. Once we receive the returned item, we will inspect it and notify you of the status of your refund or exchange.</p>
  </div>

  <div class='mb-5'>
    <h4>Non-Refundable Items</h4>
  
    <p>Certain items are non-refundable, including:
      <ul>
        <li>Gift cards</li>
        <li>Final sale items</li>
        <li>Please note that these items are not eligible for refunds or exchanges.</li>
      </ul>
    </p>
  </div>

  <div class='mb-5'>
    <h4>Conclusion</h4>
  
    <p>At KevCat, we value our customers and want to ensure their satisfaction with their purchases. Our refund policy reflects our commitment to providing excellent customer service. If you have any questions or concerns regarding our refund policy, please do not hesitate to contact us.</p>
  </div>

</section>

{% endblock %}